server:
  port: 8088
  context-path: /springboot-demo
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/我要变强?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver